services:
  - type: web
    name: focas-api
    runtime: python
    region: singapore
    buildCommand: pip install -r requirements.txt
    startCommand: python -m focas_api.server
    envVars:
      - key: FOCAS_API_KEY
        sync: false
      - key: PORT
        value: 10000
