from __future__ import annotations

import re
from typing import Iterable

# Conservative placeholder detector for FOCAS input gates.
# It catches template/default text that should not be treated as real basic facts.
PLACEHOLDER_EXACT = {
    "", "-", "--", "—", "n/a", "na", "none", "null",
    "tbd", "todo", "待补", "待填写", "待补充", "未填", "未填写", "未确认", "未知", "暂无", "无资料",
    "说明", "示例", "占位", "placeholder", "example",
    "主队名称", "客队名称", "赛事名称", "比赛时间", "比赛阶段",
    "决赛/半决赛/联赛第x轮/小组赛第x轮",
    "联赛/淘汰赛/决赛/小组赛",
    "无/有加时点球/两回合规则",
}

PLACEHOLDER_CONTAINS = (
    "待补", "待填", "待确认", "暂无", "未知", "未识别", "placeholder", "example", "todo", "tbd",
)

# Template phrases generated by old examples. If these pass the basic gate, the
# engine will treat a fake context as complete and produce unsafe downstream logic.
TEMPLATE_PHRASES = (
    "排名说明", "积分说明", "近况说明", "进攻状态说明", "防守状态说明",
    "伤停/复出/阵容完整度说明", "阵容完整度说明", "赛程体能说明", "战意说明",
    "人气/名气/冠军叙事说明", "近期重大比赛表现说明", "场地适应性说明",
    "总体交锋说明", "近年交锋说明", "同赛事交锋说明", "最近一次关键交锋说明",
    "往绩对市场心理影响说明", "现代骨架查表联赛口径",
)

TEMPLATE_ROUND_RE = re.compile(r"(?:第\s*[xｘ]\s*轮|[xｘ]\s*轮)", re.IGNORECASE)
MULTI_OPTION_RE = re.compile(r"[^/／\s]+(?:\s*[/／]\s*[^/／\s]+){2,}")


def _norm(value: object) -> str:
    return str(value).strip().lower().replace("　", " ")


def _is_multi_option_template(text: str) -> bool:
    if not MULTI_OPTION_RE.fullmatch(text):
        return False
    parts = [part.strip() for part in re.split(r"[/／]", text)]
    if any(TEMPLATE_ROUND_RE.search(part) for part in parts):
        return True
    return all(re.fullmatch(r"[a-z0-9_-]{1,12}", part, re.IGNORECASE) for part in parts)


def is_placeholder_text(value: object) -> bool:
    """Return True when a value is empty/template-like rather than factual.

    The detector is deliberately conservative for long narrative strings: a real
    sentence may contain words like “未知” as a caveat, so substring matching is
    only treated as hard failure for short strings or known template phrases.
    """
    if value is None:
        return True
    if isinstance(value, bool):
        return False
    if isinstance(value, (int, float)):
        return False
    text_raw = str(value).strip()
    text = _norm(value)
    if text in PLACEHOLDER_EXACT:
        return True
    if text_raw in TEMPLATE_PHRASES:
        return True
    if any(phrase in text_raw for phrase in TEMPLATE_PHRASES):
        return True
    if TEMPLATE_ROUND_RE.search(text_raw):
        return True
    if _is_multi_option_template(text_raw):
        return True
    if len(text) <= 24 and any(marker in text for marker in PLACEHOLDER_CONTAINS):
        return True
    # Extremely generic Chinese field values ending in “说明” are usually old
    # template placeholders, not match facts.
    if len(text_raw) <= 18 and text_raw.endswith("说明"):
        return True
    return False


def invalid_list_items(values: Iterable[object]) -> list[str]:
    return [str(v) for v in values if is_placeholder_text(v)]
